import { RiskLevel, Patient, Sex } from './types';

export const APP_STRINGS = {
  en: {
    NAV: {
      PATIENT: 'Patient',
      RECORD: 'Record',
      EPIDEMIC: 'Endemic',
      ASSIST: 'Assist',
      PHARMACY: 'Pharmacy',
      SETTINGS: 'Settings',
      ARCHIVE: 'Archive'
    },
    UNITS: {
      BP: 'mmHg',
      HR: 'bpm',
      TEMP: '°C',
      SPO2: '%',
      WEEKS: 'w',
      YEARS: 'y'
    },
    ROLES: {
      PATIENT: 'Patient',
      CAREGIVER: 'Caregiver',
      CLINICIAN: 'Clinician'
    },
    LABELS: {
      AGE: 'Age',
      SEX: 'Sex',
      BLOOD: 'Blood',
      PREGNANT: 'Pregnant',
      UNKNOWN: 'Unknown',
      STEP: 'Step',
      HOSPITAL: 'Hospital',
      MATCH: 'Match',
      SYS: 'Sys',
      DIA: 'Dia',
      HR: 'Heart Rate',
      TEMP: 'Temp',
      SPO2: 'SpO₂',
      REPORTING_AS: 'Reporting as:',
      VIEW_MEDIA: 'View Media',
      ANALYZE_SYMPTOMS: 'Analyze Symptoms with AI',
      RECORDING: 'Recording...',
      READY: 'Ready',
      AI_TRANSCRIPTION: 'AI Transcription',
      AI_ANALYZING: 'AI is analyzing...',
      AI_INSIGHT: 'AI Insight',
      VERIFIED_LOCATIONS: 'Verified Locations',
      DIFFERENTIAL: 'Differential Analysis',
      ACTIONS: 'Recommended Actions',
      OTC: 'Self-Care / OTC Options',
      DANGER_SIGNS: 'Danger Signs to Monitor',
      DISMISS: 'Dismiss',
      SECURITY: 'Data Security',
      ENCRYPTED_LOCAL: 'Locally Encrypted',
      PRIVACY_ON: 'Device Privacy On',
      ENCRYPTION_DESC: 'All clinical records are encrypted before storage in your browser\'s private sandbox. No raw text is saved to disk.',
      LOCATION_SETTINGS: 'Localization',
      PREF_LANG: 'Preferred Language',
      DEV_TOOLS: 'Developer Tools',
      DATA_SYNC: 'Data & Sync',
      CLOUD_SYNC: 'Cloud Sync',
      MANAGE_DATA: 'Manage My Data',
      DELETE_ALL: 'Delete All App Data',
      EXPORT: 'Export My Data',
      ADD_ANOTHER: 'Add Another Record',
      CHANGE: 'Change',
      GOTO_PATIENT: 'Go to Patient',
      SELECT_PATIENT_FIRST: 'Please select or create a patient first.',
      RISK_ASSESSMENT: 'AI Risk Assessment'
    },
    COMMON: {
      SAVE: 'Save',
      CANCEL: 'Cancel',
      DELETE: 'Delete',
      EDIT: 'Edit',
      NEXT: 'Next',
      BACK: 'Back',
      EXIT: 'Exit',
      DISCARD: 'Discard and Retry',
      SAVING_TIMELINE: 'Save to Patient Timeline',
      NOT_A_DIAGNOSIS: 'This app is for triage/risk assessment only, not a medical diagnosis.',
      EMERGENCY_NOTICE: 'In case of severe emergency, stop using the app and call local emergency services immediately.',
      PROCESSING: 'AI Processing Content...',
      TRANSCRIPTION_TIP: 'Tip: You can edit the transcription above before saving.'
    },
    PATIENT: {
      TITLE: 'Patient Profile',
      CREATE_FIRST: 'Create a patient profile to begin.',
      SETUP_TITLE: 'Create Your Patient Profile',
      SETUP_DESC: 'Follow our step-by-step guide to secure medical records for triage.',
      ADD_NEW: 'Add New Profile',
      START_SETUP: 'Start Setup',
      LOAD_DEMO: 'Load Demo',
      SWITCH: 'Switch Profile',
      BMI_INDEX: 'Body Mass Index (BMI)',
      EMERGENCY_CONTACT: 'Emergency Contact',
      ALLERGIES_LABEL: 'Allergies',
      CHRONIC_MEDS: 'Chronic Meds',
      SELECT_PROFILE: 'Select Profile',
      DELETE_CONFIRM: 'Are you sure you want to delete this profile? All medical history for this person will be lost.',
      STEPS: {
        IDENTITY: 'Who is this profile for?',
        EMERGENCY: 'Emergency Contact',
        PHYSICALS: 'Physicals',
        MATERNITY: 'Maternity',
        HISTORY: 'Medical History',
        ADMIN: 'Hospital Records',
        LOCATION: 'Home Area',
        REVIEW: 'Final Review'
      },
      FIELDS: {
        NAME: 'Full Name',
        PHONE: 'Phone Number',
        AGE: 'Age',
        SEX: 'Sex',
        MARITAL_STATUS: 'Marital Status',
        HEIGHT: 'Height (cm)',
        BLOOD_TYPE: 'Blood Type',
        WEIGHT: 'Weight (kg)',
        PREGNANCY: 'Pregnant or Nursing?',
        WEEKS: 'Weeks Pregnant',
        CONDITIONS: 'Known Conditions',
        ALLERGIES: 'Allergies & Adverse Reactions',
        CHRONIC_DISEASES: 'Chronic Diseases',
        HISTORY: 'Past Medical History',
        CHRONIC_MEDS: 'Chronic Medications (Long-term)',
        CURRENT_MEDS: 'Current Medications & Dosages',
        HOSPITAL_RECORDS: 'Hospital Registration IDs',
        STREET: 'Street / Area',
        HOUSE_NUMBER: 'House Number',
        BAIRRO: 'Neighborhood',
        DISTRICT: 'District',
        CIDADE: 'City',
        COUNTRY: 'Country'
      }
    },
    EPIDEMIC: {
      TITLE: 'Endemic Screening',
      PHASE1_TITLE: 'Primary Screening',
      PHASE2_TITLE: 'Fever & Symptoms',
      PHASE3_TITLE: 'Danger Signs',
      ANALYZE: 'Analyze Risk',
      YES: 'Yes',
      NO: 'No',
      IF_YES: 'If Yes:',
      QUESTIONS: {
        TRAVEL: 'Recent travel to endemic areas?',
        EXPOSURE: 'Recent exposure to mosquitoes?',
        CLOSE_CONTACT: 'Has anyone close to you recently had malaria?',
        CHILLS: 'Are you experiencing chills or shivering?',
        FEVER_NOW: 'Do you currently have a fever?',
        FEVER_DAYS: 'How many days have you had a fever?',
        FEVER_TYPE: 'Is the fever:',
        CONTINUOUS: 'Continuous',
        INTERMITTENT: 'Intermittent',
        TEMP: 'Temperature (°C)',
        WHERE: 'Where:',
        HEADACHE: 'Headache?',
        MUSCLE_ACHE: 'Muscle aches?',
        FATIGUE: 'Extreme fatigue?',
        VOMITING: 'Nausea or vomiting?',
        DIARRHEA: 'Diarrhea?',
        ABDOMINAL_PAIN: 'Abdominal pain?',
        EAT_NORMAL: 'Can you eat normally?',
        DRINK_NORMAL: 'Can you drink fluids normally?',
        CONFUSION: 'Confusion?',
        BREATHING: 'Difficulty breathing?',
        DARK_URINE: 'Very dark urine?',
        JAUNDICE: 'Yellow eyes or skin (jaundice)?',
        CANT_STAND: 'Cannot stand or walk?',
        SEIZURES: 'Seizures?',
        SEVERE_PAIN: 'Severe abdominal pain?'
      }
    },
    RECORD: {
      TITLE: 'Clinical Record',
      CAPTURE_TITLE: 'Clinical Media Capture',
      CAPTURE_DESC: 'Attach files to record',
      TAKE_PHOTO: 'Take Photo',
      RECORD_VIDEO: 'Record Video',
      VOICE_NOTE: 'Voice Note',
      UPLOAD_FILE: 'Upload File',
      TEMPLATES: ['Fever', 'Cough', 'Diarrhea', 'Rash', 'Pain', 'Other'],
      PLACEHOLDER: 'Describe symptoms, notes, or what happened...',
      EMPTY: 'No visit records yet for this patient.',
      HISTORY_TITLE: 'Clinical History',
      OBS_NOTES: 'Observation Notes',
      ATTACH_DOC: 'Attach Document',
      VITALS_TITLE: 'Vital Signs (Optional)'
    },
    ASSIST: {
      TITLE: 'AI Assist Triage',
      RUN: 'Run Risk Assessment',
      EMERGENCY_SCRIPT_TITLE: 'Emergency Call Script',
      EMERGENCY_SCRIPT_SUB: 'Help is coming. Read this clearly.',
      EMERGENCY_CALL: 'CALL EMERGENCY NOW',
      EMERGENCY_BTN: 'Call Emergency Service',
      EMERGENCY_SCRIPT: 'I am calling to report a medical emergency for a patient. Name: [NAME], Age: [AGE]. They are currently experiencing [SYMPTOMS]. Our location is [LOCATION].',
      ANALYZING: 'Analyzing health risk...',
      EMPTY_DESC: 'Enter vital signs and symptoms in the Record tab to start a risk assessment.'
    }
  },
  pt: {
    NAV: {
      PATIENT: 'Paciente',
      RECORD: 'Registo',
      EPIDEMIC: 'Endémico',
      ASSIST: 'Assistência',
      PHARMACY: 'Farmácia',
      SETTINGS: 'Configurações',
      ARCHIVE: 'Arquivo'
    },
    UNITS: {
      BP: 'mmHg',
      HR: 'bpm',
      TEMP: '°C',
      SPO2: '%',
      WEEKS: 'sem',
      YEARS: 'A'
    },
    ROLES: {
      PATIENT: 'paciente',
      CAREGIVER: 'Cuidador',
      CLINICIAN: 'Clínico'
    },
    LABELS: {
      AGE: 'Idade',
      SEX: 'Sexo',
      BLOOD: 'Sangue',
      PREGNANT: 'Grávida',
      UNKNOWN: 'Desconhecido',
      STEP: 'Passo',
      HOSPITAL: 'Hospital',
      MATCH: 'Correspondência',
      SYS: 'Sist',
      DIA: 'Pressão Arterial',
      HR: 'Frequência cardíaca',
      TEMP: 'Temp',
      SPO2: 'SatO2',
      REPORTING_AS: 'Reportar como:',
      VIEW_MEDIA: 'Ver Mídia',
      ANALYZE_SYMPTOMS: 'Analisar Sintomas com IA',
      RECORDING: 'Gravando...',
      READY: 'Pronto',
      AI_TRANSCRIPTION: 'Transcrição por IA',
      AI_ANALYZING: 'IA está analisando...',
      AI_INSIGHT: 'Percepção da IA',
      VERIFIED_LOCATIONS: 'Locais Verificados',
      DIFFERENTIAL: 'Análise Diferencial',
      ACTIONS: 'Ações Recomendadas',
      OTC: 'Opções de Auto-cuidado / OTC',
      DANGER_SIGNS: 'Sinais de Perigo a Monitorar',
      DISMISS: 'Fechar',
      SECURITY: 'Proteção de dados',
      ENCRYPTED_LOCAL: 'Encriptação local',
      PRIVACY_ON: 'Privacidade',
      ENCRYPTION_DESC: 'Todos os registos clinicos são encriptados antes do armazenamento no ambiente de trabalho privado do seu navegador.',
      LOCATION_SETTINGS: 'Localização',
      PREF_LANG: 'Idioma Preferido',
      DEV_TOOLS: 'Ferramentas do Programador',
      DATA_SYNC: 'Dados e Sincronização',
      CLOUD_SYNC: 'Sincronização na Nuvem',
      MANAGE_DATA: 'Gerir Meus Dados',
      DELETE_ALL: 'Excluir Todos os Dados',
      EXPORT: 'Exportar Meus Dados',
      ADD_ANOTHER: 'Adicionar Outro Registro',
      CHANGE: 'Alterar',
      GOTO_PATIENT: 'Ir para Paciente',
      SELECT_PATIENT_FIRST: 'Por favor, selecione ou crie um paciente primeiro.',
      RISK_ASSESSMENT: 'Avaliação de Risco por IA'
    },
    COMMON: {
      SAVE: 'Gravar',
      CANCEL: 'Cancelar',
      DELETE: 'Excluir',
      EDIT: 'Editar',
      NEXT: 'Próximo',
      BACK: 'Voltar',
      EXIT: 'Sair',
      DISCARD: 'Descartar e Repetir',
      SAVING_TIMELINE: 'Salvar no Histórico do Paciente',
      NOT_A_DIAGNOSIS: 'Este aplicativo é apenas para triagem/avaliação de risco, não um diagnóstico médico.',
      EMERGENCY_NOTICE: 'Em caso de emergência grave, pare de usar o aplicativo e ligue imediatamente para os serviços de emergência locais.',
      PROCESSING: 'IA Processando Conteúdo...',
      TRANSCRIPTION_TIP: 'Dica: Você pode editar a transcrição acima antes de salvar.'
    },
    PATIENT: {
      TITLE: 'Perfil do Paciente',
      CREATE_FIRST: 'Crie um perfil de paciente para começar.',
      SETUP_TITLE: 'Crie o Perfil do Paciente',
      SETUP_DESC: 'Siga nosso guia passo a passo para proteger os registros médicos para triagem.',
      ADD_NEW: 'Novo Perfil',
      START_SETUP: 'Iniciar Configuração',
      LOAD_DEMO: 'Carregar Demo',
      SWITCH: 'Trocar Perfil',
      BMI_INDEX: 'Índice de Massa Corporal (IMC)',
      EMERGENCY_CONTACT: 'Contato de Emergência',
      ALLERGIES_LABEL: 'Alergias',
      CHRONIC_MEDS: 'Medicação Crónica',
      SELECT_PROFILE: 'Selecionar Perfil',
      DELETE_CONFIRM: 'Tem certeza de que deseja excluir este perfil? Todo o histórico médico desta pessoa será perdido.',
      STEPS: {
        IDENTITY: 'Para quem é este perfil?',
        EMERGENCY: 'Contato de Emergência',
        PHYSICALS: 'Dados Físicos',
        MATERNITY: 'Maternidade',
        HISTORY: 'Histórico Médico',
        ADMIN: 'Registros Hospitalares',
        LOCATION: 'Área de Residência',
        REVIEW: 'Revisão Final'
      },
      FIELDS: {
        NAME: 'Nome Completo',
        PHONE: 'Número de Telefone',
        AGE: 'Idade',
        SEX: 'Sexo',
        MARITAL_STATUS: 'Estado Civil',
        HEIGHT: 'Altura (cm)',
        BLOOD_TYPE: 'Tipo Sanguíneo',
        WEIGHT: 'Peso (kg)',
        PREGNANCY: 'Grávida ou Amamentando?',
        WEEKS: 'Semanas de Gravidez',
        CONDITIONS: 'Condições Conhecidas',
        ALLERGIES: 'Alergias e Reações Adversas',
        CHRONIC_DISEASES: 'Doenças Crónicas',
        HISTORY: 'Histórico Médico Passado',
        CHRONIC_MEDS: 'Medicamentos Crónicos (Longo Prazo)',
        CURRENT_MEDS: 'Medicamentos Atuais e Dosagens',
        HOSPITAL_RECORDS: 'IDs de Registro Hospitalar',
        STREET: 'Rua / Área',
        HOUSE_NUMBER: 'Nº de Casa',
        BAIRRO: 'Bairro',
        DISTRICT: 'Distrito',
        CIDADE: 'Cidade',
        COUNTRY: 'País'
      }
    },
    EPIDEMIC: {
      TITLE: 'Rastreio de doença Endémica',
      PHASE1_TITLE: 'Triagem Primária',
      PHASE2_TITLE: 'Febre e Sintomas',
      PHASE3_TITLE: 'Sinais de Perigo',
      ANALYZE: 'Analisar Risco',
      YES: 'Sim',
      NO: 'Não',
      IF_YES: 'Se Sim:',
      QUESTIONS: {
        TRAVEL: 'Viagem recente para áreas endémicas?',
        EXPOSURE: 'Exposição recente a mosquitos?',
        CLOSE_CONTACT: 'Alguém próximo teve malária recentemente?',
        CHILLS: 'Está a sentir calafrios ou tremores?',
        FEVER_NOW: 'Tem febre atualmente?',
        FEVER_DAYS: 'Há quantos dias tem febre?',
        FEVER_TYPE: 'A febre é:',
        CONTINUOUS: 'Contínua',
        INTERMITTENT: 'Intermitente',
        TEMP: 'Temperatura (°C)',
        WHERE: 'Onde:',
        HEADACHE: 'Dor de cabeça?',
        MUSCLE_ACHE: 'Dores musculares?',
        FATIGUE: 'Extrema fadiga?',
        VOMITING: 'Náuseas ou vómitos?',
        DIARRHEA: 'Diarreia?',
        ABDOMINAL_PAIN: 'Dor abdominal?',
        EAT_NORMAL: 'Consegue comer normalmente?',
        DRINK_NORMAL: 'Consegue beber líquidos normalmente?',
        CONFUSION: 'Confusão mental?',
        BREATHING: 'Dificuldade em respirar?',
        DARK_URINE: 'Urina muito escura?',
        JAUNDICE: 'Olhos ou pele amarelados (icterícia)?',
        CANT_STAND: 'Não consegue ficar de pé ou andar?',
        SEIZURES: 'Convulsões?',
        SEVERE_PAIN: 'Dor abdominal intensa?'
      }
    },
    RECORD: {
      TITLE: 'Registo Clínico',
      CAPTURE_TITLE: 'Captura de Mídia Clínica',
      CAPTURE_DESC: 'Anexar arquivos ao registro',
      TAKE_PHOTO: 'Tirar Foto',
      RECORD_VIDEO: 'Registo de Vídeo',
      VOICE_NOTE: 'Nota de Voz',
      UPLOAD_FILE: 'Carregar Arquivo',
      TEMPLATES: ['Febre', 'Tosse', 'Diarreia', 'Erupção', 'Dor', 'Outro'],
      PLACEHOLDER: 'Descreva os sintomas, notas ou o que aconteceu...',
      EMPTY: 'Notas clínicas e sinais vitais',
      HISTORY_TITLE: 'Histórico Clínico',
      OBS_NOTES: 'Observação',
      ATTACH_DOC: 'Anexar Documento',
      VITALS_TITLE: 'Sinais Vitais (Opcional)'
    },
    ASSIST: {
      TITLE: 'Triagem por IA',
      RUN: 'Iniciar Avaliação de Risco',
      EMERGENCY_SCRIPT_TITLE: 'Roteiro de Chamada de Emergência',
      EMERGENCY_SCRIPT_SUB: 'A ajuda está a caminho. Leia isto claramente.',
      EMERGENCY_CALL: 'LIGAR PARA EMERGÊNCIA AGORA',
      EMERGENCY_BTN: 'Ligar para Serviço de Emergência',
      EMERGENCY_SCRIPT: 'Estou ligando para relatar uma emergência médica. Nome: [NAME], Idade: [AGE]. Eles estão apresentando [SYMPTOMS]. Nossa localização é [LOCATION].',
      ANALYZING: 'Avaliando...',
      EMPTY_DESC: 'Notas clínicas e sinais vitais'
    }
  }
};

export const DEMO_PATIENT: Patient = {
  id: "demo-amina-001",
  fullName: "Amina Nkosi",
  phoneNumber: "+258 84 123 4567",
  emergencyContact: {
    name: "John Nkosi",
    relationship: "Husband",
    phone: "+258 82 987 6543"
  },
  sex: Sex.FEMALE,
  age: 28,
  height: 162,
  weight: 68,
  bloodType: 'O+',
  race: 'Black',
  maritalStatus: 'Married',
  hospitalRecords: [
    { hospitalName: "Hospital Central de Maputo", registrationNumber: "HCM-2024-8842" },
    { hospitalName: "C.S. de Maxaquene", registrationNumber: "MXQ-991" }
  ],
  isPregnantOrBreastfeeding: true,
  pregnancyWeeks: 28,
  knownConditions: ['Asthma'],
  allergies: "None known",
  chronicDiseases: "Childhood Asthma",
  pastMedicalHistory: "Mild intermittent asthma episodes since childhood. No past surgeries.",
  chronicMedications: "Salbutamol Inhaler (as needed)",
  currentMedications: "Prenatal Vitamins (daily), Folic Acid 400mcg (daily)",
  location: {
    street: "Avenida da Unidade",
    houseNumber: "124",
    bairro: "Bairro de Maxaquene",
    distrito: "KaMaxaquene",
    cidade: "Maputo",
    provincia: "Maputo Cidade",
    country: "Moçambique"
  }
};

export const MOCK_PATIENTS: Patient[] = [];